require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/StructInheritance:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ["heredoc"]
  Max: 12

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

Layout/HeredocIndentation:
  Enabled: false
